name: Build

on:
  push:
    tags:
      - 'v*'
      - 'v*-prerelease'
      - 'v*-dev'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to upload the release

    strategy:
      matrix:
        platform: [linux, macos, windows]  # Build for all three platforms
        macos_arch: [x64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install Dependencies
        run: npm install

      - name: Build app for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "linux" ]; then
            npx electron-builder --linux --x64 --AppImage
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            npx electron-builder --mac --${{ matrix.macos_arch }} --zip
          elif [ "${{ matrix.platform }}" == "windows" ]; then
            npx electron-builder --win --x64 --zip
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release for ${{ matrix.platform }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            dist/*.AppImage  # For Linux
            dist/*.zip       # For Windows and Mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
